COURSES: dict[str, dict] = {
    "英語": {
        "instructor": "野原",
        "format": "対面",
        "classification": "教養言語",
        "content": "発話が中心",
        "evaluation": "プレゼンとテストとシュッ石器",
        "rating": 4,
        "ease_rating": "A",
        "comment": "ｗｗｗｗｗｗｗｗｗっうぇうぇえええええええええええうぇうぇうぇうぇうぇうぇうぇうぇっうぇえっうぇえｗ",
        "syllabus_url": "",
    },
    "微分積分学Ⅰ": {
        "instructor": "山田教授",
        "format": "対面",
        "classification": "専門必修",
        "content": "微分・積分の基礎",
        "evaluation": "期末試験80%、小テスト20%",
        "rating": 4,
        "ease_rating": "A",
        "comment": "過去問がかなり重要。",
        "syllabus_url": "",
    },
    "線形代数学Ⅰ": {
        "instructor": "佐藤教授",
        "format": "対面",
        "classification": "専門必修",
        "content": "行列とベクトル",
        "evaluation": "期末試験100%",
        "rating": 3,
        "ease_rating": "B",
        "comment": "毎週復習しないと後半で詰む。",
        "syllabus_url": "",
    },
    "英語コミュニケーションA": {
        "instructor": "Smith先生",
        "format": "対面",
        "classification": "教養",
        "content": "英会話とディスカッション",
        "evaluation": "出席40%、課題60%",
        "rating": 5,
        "ease_rating": "S",
        "comment": "楽しく単位が取れる。",
        "syllabus_url": "",
    },
    "情報リテラシー": {
        "instructor": "中村准教授",
        "format": "オンデマンド",
        "classification": "教養",
        "content": "PC操作と情報倫理",
        "evaluation": "レポート100%",
        "rating": 5,
        "ease_rating": "SS",
        "comment": "かなり楽。",
        "syllabus_url": "",
    },
    "力学基礎": {
        "instructor": "田中教授",
        "format": "対面",
        "classification": "専門必修",
        "content": "ニュートン力学",
        "evaluation": "中間30%、期末70%",
        "rating": 3,
        "ease_rating": "B",
        "comment": "演習問題を解くこと。",
        "syllabus_url": "",
    },
    "日本文化論": {
        "instructor": "高橋教授",
        "format": "オンデマンド",
        "classification": "教養",
        "content": "日本文化の歴史",
        "evaluation": "レポート100%",
        "rating": 4,
        "ease_rating": "S",
        "comment": "レポートは早めに。",
        "syllabus_url": "",
    },
    "プログラミング入門": {
        "instructor": "伊藤准教授",
        "format": "対面",
        "classification": "専門選択",
        "content": "Python基礎",
        "evaluation": "課題70%、試験30%",
        "rating": 5,
        "ease_rating": "A",
        "comment": "初心者にも優しい。",
        "syllabus_url": "",
    },
    "経済学概論": {
        "instructor": "小林教授",
        "format": "リアルタイム配信",
        "classification": "教養",
        "content": "ミクロ・マクロ経済学",
        "evaluation": "試験100%",
        "rating": 3,
        "ease_rating": "B",
        "comment": "用語暗記が大事。",
        "syllabus_url": "",
    },
    "物理学実験": {
        "instructor": "木村教授",
        "format": "対面",
        "classification": "専門必修",
        "content": "基礎実験",
        "evaluation": "レポート100%",
        "rating": 2,
        "ease_rating": "C",
        "comment": "レポートが重い。",
        "syllabus_url": "",
    },
    "心理学入門": {
        "instructor": "橋本教授",
        "format": "オンデマンド",
        "classification": "教養",
        "content": "心理学の基礎",
        "evaluation": "小テスト50%、レポート50%",
        "rating": 5,
        "ease_rating": "S",
        "comment": "内容が面白い。",
        "syllabus_url": "",
    },
    "化学基礎": {
        "instructor": "森教授",
        "format": "対面",
        "classification": "専門必修",
        "content": "化学反応と熱力学",
        "evaluation": "試験80%、課題20%",
        "rating": 3,
        "ease_rating": "B",
        "comment": "計算問題対策必須。",
        "syllabus_url": "",
    },
    "統計学入門": {
        "instructor": "石井教授",
        "format": "対面",
        "classification": "教養",
        "content": "統計の基礎",
        "evaluation": "試験70%、課題30%",
        "rating": 4,
        "ease_rating": "A",
        "comment": "実生活にも役立つ。",
        "syllabus_url": "",
    },
    "フランス語Ⅰ": {
        "instructor": "Dubois先生",
        "format": "対面",
        "classification": "外国語",
        "content": "フランス語初級",
        "evaluation": "小テスト50%、期末50%",
        "rating": 4,
        "ease_rating": "A",
        "comment": "発音練習が楽しい。",
        "syllabus_url": "",
    },
    "環境科学概論": {
        "instructor": "岡田教授",
        "format": "オンデマンド",
        "classification": "教養",
        "content": "環境問題全般",
        "evaluation": "レポート100%",
        "rating": 5,
        "ease_rating": "SS",
        "comment": "楽単として有名。",
        "syllabus_url": "",
    },
    "機械設計基礎": {
        "instructor": "吉田教授",
        "format": "対面",
        "classification": "専門選択",
        "content": "CADと設計基礎",
        "evaluation": "課題60%、試験40%",
        "rating": 4,
        "ease_rating": "A",
        "comment": "将来役立つ。",
        "syllabus_url": "",
    },
    "哲学入門": {
        "instructor": "西村教授",
        "format": "オンデマンド",
        "classification": "教養",
        "content": "西洋哲学史",
        "evaluation": "レポート100%",
        "rating": 3,
        "ease_rating": "A",
        "comment": "考えるのが好きなら面白い。",
        "syllabus_url": "",
    },
    "データサイエンス基礎学": {
        "instructor": "松本教授",
        "format": "リアルタイム配信",
        "classification": "教養",
        "content": "データ分析入門",
        "evaluation": "課題70%、テスト30%",
        "rating": 5,
        "ease_rating": "S",
        "comment": "今後の時代に役立つ。",
        "syllabus_url": "https://kym22-web.ofc.kobe-u.ac.jp/campusweb/campussquare.do?_flowExecutionKey=_c59222843-F954-7D74-B7C4-29AE6CD8FB5C_k6D37F1EE-7F54-A7C1-8637-308EFF746F32",
    },
    "生物学概論": {
        "instructor": "山本教授",
        "format": "対面",
        "classification": "教養",
        "content": "生物の仕組み",
        "evaluation": "試験100%",
        "rating": 3,
        "ease_rating": "B",
        "comment": "暗記量が多め。",
        "syllabus_url": "",
    },
    "キャリアデザイン": {
        "instructor": "外部講師",
        "format": "オンデマンド",
        "classification": "教養",
        "content": "キャリア形成",
        "evaluation": "レポート100%",
        "rating": 5,
        "ease_rating": "SS",
        "comment": "出席感覚で取れる。",
        "syllabus_url": "",
    },
    "AIと社会": {
        "instructor": "藤井教授",
        "format": "リアルタイム配信",
        "classification": "教養",
        "content": "AIの活用と倫理",
        "evaluation": "レポート50%、発表50%",
        "rating": 5,
        "ease_rating": "S",
        "comment": "内容が新しくて面白い。",
        "syllabus_url": "",
    },
}
